//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUKWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersRegistring
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public int RollNo { get; set; }
        public System.DateTime JoiningYear { get; set; }
        public System.DateTime LeavingYear { get; set; }
        public string Designation { get; set; }
        public string Posting { get; set; }
        public string BloodGroup { get; set; }
        public string House { get; set; }
        public string Department { get; set; }
        public string School { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ProfileLink { get; set; }
    }
}
