//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUKWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Requirements
    {
        public int col_RequirementID { get; set; }
        public string col_RequirementCategory { get; set; }
        public string col_RequirementDescription { get; set; }
        public string col_RequirementContact { get; set; }
        public string col_RequirementEmail { get; set; }
        public string col_PostedBy { get; set; }
        public System.DateTime col_RequirementPostedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
