//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUKWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Jobs
    {
        public int col_JobID { get; set; }
        public string col_JobTitle { get; set; }
        public string col_JobDescription { get; set; }
        public System.DateTime col_PostDateTime { get; set; }
        public bool col_Expired { get; set; }
        public string col_Category { get; set; }
        public string col_ContactNumber { get; set; }
        public string col_ContactEmail { get; set; }
        public string col_PostedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
