//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUKWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Photo
    {
        public int col_PhotoID { get; set; }
        public byte[] col_Photo { get; set; }
        public string col_UserId { get; set; }
        public byte[] col_BigPhoto { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
