package com.track24x7.kuk.activity;

import android.Manifest;
import android.app.AlertDialog;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Build;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.RequiresApi;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Toast;

import com.android.volley.AuthFailureError;
import com.android.volley.NetworkResponse;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.ServerError;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.HttpHeaderParser;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;
import com.google.android.gms.ads.AdListener;
import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.InterstitialAd;
import com.google.gson.Gson;
import com.track24x7.kuk.R;
import com.track24x7.kuk.adapter.SearchAdapter;
import com.track24x7.kuk.app.config;
import com.track24x7.kuk.pojo.SearchPOJO;
import com.track24x7.kuk.progress.ProgressHUD;
import com.track24x7.kuk.util.Pref;
import com.track24x7.kuk.util.StringUtils;
import com.track24x7.kuk.util.TagUtils;
import com.track24x7.kuk.util.ToastClass;
import com.track24x7.kuk.util.UtilFunction;
import com.track24x7.kuk.webservice.WebServicesUrls;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import butterknife.BindView;
import butterknife.ButterKnife;

public class SearchActivity extends BaseMenuActivity {

    @BindView(R.id.se_spinner_city)
    Spinner se_spinner_city;
    @BindView(R.id.se_spinner_Professions)
    Spinner se_spinner_Professions;
    @BindView(R.id.se_spinner_Batch)
    Spinner se_spinner_Batch;
    @BindView(R.id.se_spinner_institute)
    Spinner se_spinner_institute;
    /*@BindView(R.id.se_roll_no)
    EditText se_roll_no;*/
    @BindView(R.id.se_department)
    EditText se_department;
    @BindView(R.id.se_designation)
    EditText se_designation;
    @BindView(R.id.se_btn_search)
    Button se_btn_search;int check = 0;
    @BindView(R.id.se_first_name)
    EditText se_first_name;
    @BindView(R.id.se_last_name)
    EditText se_last_name;
    public void alert(String str) {
        AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(this);
        alertDialogBuilder.setTitle("Alert!").setMessage(str).setPositiveButton("Ok", new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialog, int which) {

            }
        }).show();
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_search);
        ButterKnife.bind(this);
        se_btn_search.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Search();
            }
        });
        Bundle b = getIntent().getExtras();
        String value = b.getString("Screen");
        getSupportActionBar().setTitle(value);
        setSpinnerItems();
    }

    public void setSpinnerItems(){

        int startingYear = 1960;
        List<String> yearList = new ArrayList<>();
        yearList.add("All Batches");
        while (startingYear < 2019) {
            startingYear = startingYear + 1;
            yearList.add(String.valueOf(startingYear));
        }


        ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this,
                android.R.layout.simple_spinner_item, yearList);
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        se_spinner_Batch.setAdapter(dataAdapter);


        List<String> city=new ArrayList<>();
        city.add("All Cities");
        city.add("Adilabad");
        city.add("Agra");
        city.add("Ahmedabad");
        city.add("Ahmednagar");
        city.add("Aizawl");
        city.add("Ajitgarh (Mohali)");
        city.add("Ajmer");
        city.add("Akola");
        city.add("Alappuzha");
        city.add("Aligarh");
        city.add("Alirajpur");
        city.add("Allahabad");
        city.add("Almora");
        city.add("Alwar");
        city.add("Ambala");
        city.add("Ambedkar Nagar");
        city.add("Amravati");
        city.add("Amreli district");
        city.add("Amritsar");
        city.add("Anand");
        city.add("Anantapur");
        city.add("Anantnag");
        city.add("Angul");
        city.add("Anjaw");
        city.add("Anuppur");
        city.add("Araria");
        city.add("Ariyalur");
        city.add("Arwal");
        city.add("Ashok Nagar");
        city.add("Auraiya");
        city.add("Aurangabad");
        city.add("Aurangabad");
        city.add("Azamgarh");
        city.add("Badgam");
        city.add("Bagalkot");
        city.add("Bageshwar");
        city.add("Bagpat");
        city.add("Bahraich");
        city.add("Baksa");
        city.add("Balaghat");
        city.add("Balangir");
        city.add("Balasore");
        city.add("Ballia");
        city.add("Balrampur");
        city.add("Banaskantha");
        city.add("Banda");
        city.add("Bandipora");
        city.add("Bangalore Rural");
        city.add("Bangalore Urban");
        city.add("Banka");
        city.add("Bankura");
        city.add("Banswara");
        city.add("Barabanki");
        city.add("Baramulla");
        city.add("Baran");
        city.add("Bardhaman");
        city.add("Bareilly");
        city.add("Bargarh (Baragarh)");
        city.add("Barmer");
        city.add("Barnala");
        city.add("Barpeta");
        city.add("Barwani");
        city.add("Bastar");
        city.add("Basti");
        city.add("Bathinda");
        city.add("Beed");
        city.add("Begusarai");
        city.add("Belgaum");
        city.add("Bellary");
        city.add("Betul");
        city.add("Bhadrak");
        city.add("Bhagalpur");
        city.add("Bhandara");
        city.add("Bharatpur");
        city.add("Bharuch");
        city.add("Bhavnagar");
        city.add("Bhilwara");
        city.add("Bhind");
        city.add("Bhiwani");
        city.add("Bhojpur");
        city.add("Bhopal");
        city.add("Bidar");
        city.add("Bijapur");
        city.add("Bijapur");
        city.add("Bijnor");
        city.add("Bikaner");
        city.add("Bilaspur");
        city.add("Bilaspur");
        city.add("Birbhum");
        city.add("Bishnupur");
        city.add("Bokaro");
        city.add("Bongaigaon");
        city.add("Boudh (Bauda)");
        city.add("Budaun");
        city.add("Bulandshahr");
        city.add("Buldhana");
        city.add("Bundi");
        city.add("Burhanpur");
        city.add("Buxar");
        city.add("Cachar");
        city.add("Central Delhi");
        city.add("Chamarajnagar");
        city.add("Chamba");
        city.add("Chamoli");
        city.add("Champawat");
        city.add("Champhai");
        city.add("Chandauli");
        city.add("Chandel");
        city.add("Chandigarh");
        city.add("Chandrapur");
        city.add("Changlang");
        city.add("Chatra");
        city.add("Chennai");
        city.add("Chhatarpur");
        city.add("Chhatrapati Shahuji Maharaj Nagar");
        city.add("Chhindwara");
        city.add("Chikkaballapur");
        city.add("Chikkamagaluru");
        city.add("Chirang");
        city.add("Chitradurga");
        city.add("Chitrakoot");
        city.add("Chittoor");
        city.add("Chittorgarh");
        city.add("Churachandpur");
        city.add("Churu");
        city.add("Coimbatore");
        city.add("Cooch Behar");
        city.add("Cuddalore");
        city.add("Cuttack");
        city.add("Dadra and Nagar Haveli");
        city.add("Dahod");
        city.add("Dakshin Dinajpur");
        city.add("Dakshina Kannada");
        city.add("Daman");
        city.add("Damoh");
        city.add("Dantewada");
        city.add("Darbhanga");
        city.add("Darjeeling");
        city.add("Darrang");
        city.add("Datia");
        city.add("Dausa");
        city.add("Davanagere");
        city.add("Debagarh (Deogarh)");
        city.add("Dehradun");
        city.add("Deoghar");
        city.add("Deoria");
        city.add("Dewas");
        city.add("Dhalai");
        city.add("Dhamtari");
        city.add("Dhanbad");
        city.add("Dhar");
        city.add("Dharmapuri");
        city.add("Dharwad");
        city.add("Dhemaji");
        city.add("Dhenkanal");
        city.add("Dholpur");
        city.add("Dhubri");
        city.add("Dhule");
        city.add("Dibang Valley");
        city.add("Dibrugarh");
        city.add("Dima Hasao");
        city.add("Dimapur");
        city.add("Dindigul");
        city.add("Dindori");
        city.add("Diu");
        city.add("Doda");
        city.add("Dumka");
        city.add("Dungapur");
        city.add("Durg");
        city.add("East Champaran");
        city.add("East Delhi");
        city.add("East Garo Hills");
        city.add("East Khasi Hills");
        city.add("East Siang");
        city.add("East Sikkim");
        city.add("East Singhbhum");
        city.add("Eluru");
        city.add("Ernakulam");
        city.add("Erode");
        city.add("Etah");
        city.add("Etawah");
        city.add("Faizabad");
        city.add("Faridabad");
        city.add("Faridkot");
        city.add("Farrukhabad");
        city.add("Fatehabad");
        city.add("Fatehgarh Sahib");
        city.add("Fatehpur");
        city.add("Fazilka");
        city.add("Firozabad");
        city.add("Firozpur");
        city.add("Gadag");
        city.add("Gadchiroli");
        city.add("Gajapati");
        city.add("Ganderbal");
        city.add("Gandhinagar");
        city.add("Ganganagar");
        city.add("Ganjam");
        city.add("Garhwa");
        city.add("Gautam Buddh Nagar");
        city.add("Gaya");
        city.add("Ghaziabad");
        city.add("Ghazipur");
        city.add("Giridih");
        city.add("Goalpara");
        city.add("Godda");
        city.add("Golaghat");
        city.add("Gonda");
        city.add("Gondia");
        city.add("Gopalganj");
        city.add("Gorakhpur");
        city.add("Gulbarga");
        city.add("Gumla");
        city.add("Guna");
        city.add("Guntur");
        city.add("Gurdaspur");
        city.add("Gurgaon");
        city.add("Gwalior");
        city.add("Hailakandi");
        city.add("Hamirpur");
        city.add("Hamirpur");
        city.add("Hanumangarh");
        city.add("Harda");
        city.add("Hardoi");
        city.add("Haridwar");
        city.add("Hassan");
        city.add("Haveri district");
        city.add("Hazaribag");
        city.add("Hingoli");
        city.add("Hissar");
        city.add("Hooghly");
        city.add("Hoshangabad");
        city.add("Hoshiarpur");
        city.add("Howrah");
        city.add("Hyderabad");
        city.add("Hyderabad");
        city.add("Idukki");
        city.add("Imphal East");
        city.add("Imphal West");
        city.add("Indore");
        city.add("Jabalpur");
        city.add("Jagatsinghpur");
        city.add("Jaintia Hills");
        city.add("Jaipur");
        city.add("Jaisalmer");
        city.add("Jajpur");
        city.add("Jalandhar");
        city.add("Jalaun");
        city.add("Jalgaon");
        city.add("Jalna");
        city.add("Jalore");
        city.add("Jalpaiguri");
        city.add("Jammu");
        city.add("Jamnagar");
        city.add("Jamtara");
        city.add("Jamui");
        city.add("Janjgir-Champa");
        city.add("Jashpur");
        city.add("Jaunpur district");
        city.add("Jehanabad");
        city.add("Jhabua");
        city.add("Jhajjar");
        city.add("Jhalawar");
        city.add("Jhansi");
        city.add("Jharsuguda");
        city.add("Jhunjhunu");
        city.add("Jind");
        city.add("Jodhpur");
        city.add("Jorhat");
        city.add("Junagadh");
        city.add("Jyotiba Phule Nagar");
        city.add("Kabirdham (formerly Kawardha)");
        city.add("Kadapa");
        city.add("Kaimur");
        city.add("Kaithal");
        city.add("Kakinada");
        city.add("Kalahandi");
        city.add("Kamrup");
        city.add("Kamrup Metropolitan");
        city.add("Kanchipuram");
        city.add("Kandhamal");
        city.add("Kangra");
        city.add("Kanker");
        city.add("Kannauj");
        city.add("Kannur");
        city.add("Kanpur");
        city.add("Kanshi Ram Nagar");
        city.add("Kanyakumari");
        city.add("Kapurthala");
        city.add("Karaikal");
        city.add("Karauli");
        city.add("Karbi Anglong");
        city.add("Kargil");
        city.add("Karimganj");
        city.add("Karimnagar");
        city.add("Karnal");
        city.add("Karur");
        city.add("Kasaragod");
        city.add("Kathua");
        city.add("Katihar");
        city.add("Katni");
        city.add("Kaushambi");
        city.add("Kendrapara");
        city.add("Kendujhar (Keonjhar)");
        city.add("Khagaria");
        city.add("Khammam");
        city.add("Khandwa (East Nimar)");
        city.add("Khargone (West Nimar)");
        city.add("Kheda");
        city.add("Khordha");
        city.add("Khowai");
        city.add("Khunti");
        city.add("Kinnaur");
        city.add("Kishanganj");
        city.add("Kishtwar");
        city.add("Kodagu");
        city.add("Koderma");
        city.add("Kohima");
        city.add("Kokrajhar");
        city.add("Kolar");
        city.add("Kolasib");
        city.add("Kolhapur");
        city.add("Kolkata");
        city.add("Kollam");
        city.add("Koppal");
        city.add("Koraput");
        city.add("Korba");
        city.add("Koriya");
        city.add("Kota");
        city.add("Kottayam");
        city.add("Kozhikode");
        city.add("Krishna");
        city.add("Kulgam");
        city.add("Kullu");
        city.add("Kupwara");
        city.add("Kurnool");
        city.add("Kurukshetra");
        city.add("Kurung Kumey");
        city.add("Kushinagar");
        city.add("Kutch");
        city.add("Lahaul and Spiti");
        city.add("Lakhimpur");
        city.add("Lakhimpur Kheri");
        city.add("Lakhisarai");
        city.add("Lalitpur");
        city.add("Latehar");
        city.add("Latur");
        city.add("Lawngtlai");
        city.add("Leh");
        city.add("Lohardaga");
        city.add("Lohit");
        city.add("Lower Dibang Valley");
        city.add("Lower Subansiri");
        city.add("Lucknow");
        city.add("Ludhiana");
        city.add("Lunglei");
        city.add("Madhepura");
        city.add("Madhubani");
        city.add("Madurai");
        city.add("Mahamaya Nagar");
        city.add("Maharajganj");
        city.add("Mahasamund");
        city.add("Mahbubnagar");
        city.add("Mahe");
        city.add("Mahendragarh");
        city.add("Mahoba");
        city.add("Mainpuri");
        city.add("Malappuram");
        city.add("Maldah");
        city.add("Malkangiri");
        city.add("Mamit");
        city.add("Mandi");
        city.add("Mandla");
        city.add("Mandsaur");
        city.add("Mandya");
        city.add("Mansa");
        city.add("Marigaon");
        city.add("Mathura");
        city.add("Mau");
        city.add("Mayurbhanj");
        city.add("Medak");
        city.add("Meerut");
        city.add("Mehsana");
        city.add("Mewat");
        city.add("Mirzapur");
        city.add("Moga");
        city.add("Mokokchung");
        city.add("Mon");
        city.add("Moradabad");
        city.add("Morena");
        city.add("Mumbai City");
        city.add("Mumbai suburban");
        city.add("Munger");
        city.add("Murshidabad");
        city.add("Muzaffarnagar");
        city.add("Muzaffarpur");
        city.add("Mysore");
        city.add("Nabarangpur");
        city.add("Nadia");
        city.add("Nagaon");
        city.add("Nagapattinam");
        city.add("Nagaur");
        city.add("Nagpur");
        city.add("Nainital");
        city.add("Nalanda");
        city.add("Nalbari");
        city.add("Nalgonda");
        city.add("Namakkal");
        city.add("Nanded");
        city.add("Nandurbar");
        city.add("Narayanpur");
        city.add("Narmada");
        city.add("Narsinghpur");
        city.add("Nashik");
        city.add("Navsari");
        city.add("Nawada");
        city.add("Nawanshahr");
        city.add("Nayagarh");
        city.add("Neemuch");
        city.add("Nellore");
        city.add("New Delhi");
        city.add("Nilgiris");
        city.add("Nizamabad");
        city.add("North 24 Parganas");
        city.add("North Delhi");
        city.add("North East Delhi");
        city.add("North Goa");
        city.add("North Sikkim");
        city.add("North Tripura");
        city.add("North West Delhi");
        city.add("Nuapada");
        city.add("Ongole");
        city.add("Osmanabad");
        city.add("Pakur");
        city.add("Palakkad");
        city.add("Palamu");
        city.add("Pali");
        city.add("Palwal");
        city.add("Panchkula");
        city.add("Panchmahal");
        city.add("Panchsheel Nagar district (Hapur)");
        city.add("Panipat");
        city.add("Panna");
        city.add("Papum Pare");
        city.add("Parbhani");
        city.add("Paschim Medinipur");
        city.add("Patan");
        city.add("Pathanamthitta");
        city.add("Pathankot");
        city.add("Patiala");
        city.add("Patna");
        city.add("Pauri Garhwal");
        city.add("Perambalur");
        city.add("Phek");
        city.add("Pilibhit");
        city.add("Pithoragarh");
        city.add("Pondicherry");
        city.add("Poonch");
        city.add("Porbandar");
        city.add("Pratapgarh");
        city.add("Pratapgarh");
        city.add("Pudukkottai");
        city.add("Pulwama");
        city.add("Pune");
        city.add("Purba Medinipur");
        city.add("Puri");
        city.add("Purnia");
        city.add("Purulia");
        city.add("Raebareli");
        city.add("Raichur");
        city.add("Raigad");
        city.add("Raigarh");
        city.add("Raipur");
        city.add("Raisen");
        city.add("Rajauri");
        city.add("Rajgarh");
        city.add("Rajkot");
        city.add("Rajnandgaon");
        city.add("Rajsamand");
        city.add("Ramabai Nagar (Kanpur Dehat)");
        city.add("Ramanagara");
        city.add("Ramanathapuram");
        city.add("Ramban");
        city.add("Ramgarh");
        city.add("Rampur");
        city.add("Ranchi");
        city.add("Ratlam");
        city.add("Ratnagiri");
        city.add("Rayagada");
        city.add("Reasi");
        city.add("Rewa");
        city.add("Rewari");
        city.add("Ri Bhoi");
        city.add("Rohtak");
        city.add("Rohtas");
        city.add("Rudraprayag");
        city.add("Rupnagar");
        city.add("Sabarkantha");
        city.add("Sagar");
        city.add("Saharanpur");
        city.add("Saharsa");
        city.add("Sahibganj");
        city.add("Saiha");
        city.add("Salem");
        city.add("Samastipur");
        city.add("Samba");
        city.add("Sambalpur");
        city.add("Sangli");
        city.add("Sangrur");
        city.add("Sant Kabir Nagar");
        city.add("Sant Ravidas Nagar");
        city.add("Saran");
        city.add("Satara");
        city.add("Satna");
        city.add("Sawai Madhopur");
        city.add("Sehore");
        city.add("Senapati");
        city.add("Seoni");
        city.add("Seraikela Kharsawan");
        city.add("Serchhip");
        city.add("Shahdol");
        city.add("Shahjahanpur");
        city.add("Shajapur");
        city.add("Shamli");
        city.add("Sheikhpura");
        city.add("Sheohar");
        city.add("Sheopur");
        city.add("Shimla");
        city.add("Shimoga");
        city.add("Shivpuri");
        city.add("Shopian");
        city.add("Shravasti");
        city.add("Sibsagar");
        city.add("Siddharthnagar");
        city.add("Sidhi");
        city.add("Sikar");
        city.add("Simdega");
        city.add("Sindhudurg");
        city.add("Singrauli");
        city.add("Sirmaur");
        city.add("Sirohi");
        city.add("Sirsa");
        city.add("Sitamarhi");
        city.add("Sitapur");
        city.add("Sivaganga");
        city.add("Siwan");
        city.add("Solan");
        city.add("Solapur");
        city.add("Sonbhadra");
        city.add("Sonipat");
        city.add("Sonitpur");
        city.add("South 24 Parganas");
        city.add("South Delhi");
        city.add("South Garo Hills");
        city.add("South Goa");
        city.add("South Sikkim");
        city.add("South Tripura");
        city.add("South West Delhi");
        city.add("Sri Muktsar Sahib");
        city.add("Srikakulam");
        city.add("Srinagar");
        city.add("Subarnapur (Sonepur)");
        city.add("Sultanpur");
        city.add("Sundergarh");
        city.add("Supaul");
        city.add("Surat");
        city.add("Surendranagar");
        city.add("Surguja");
        city.add("Tamenglong");
        city.add("Tarn Taran");
        city.add("Tawang");
        city.add("Tehri Garhwal");
        city.add("Thane");
        city.add("Thanjavur");
        city.add("The Dangs");
        city.add("Theni");
        city.add("Thiruvananthapuram");
        city.add("Thoothukudi");
        city.add("Thoubal");
        city.add("Thrissur");
        city.add("Tikamgarh");
        city.add("Tinsukia");
        city.add("Tirap");
        city.add("Tiruchirappalli");
        city.add("Tirunelveli");
        city.add("Tirupur");
        city.add("Tiruvallur");
        city.add("Tiruvannamalai");
        city.add("Tiruvarur");
        city.add("Tonk");
        city.add("Tuensang");
        city.add("Tumkur");
        city.add("Udaipur");
        city.add("Udalguri");
        city.add("Udham Singh Nagar");
        city.add("Udhampur");
        city.add("Udupi");
        city.add("Ujjain");
        city.add("Ukhrul");
        city.add("Umaria");
        city.add("Una");
        city.add("Unnao");
        city.add("Upper Siang");
        city.add("Upper Subansiri");
        city.add("Uttar Dinajpur");
        city.add("Uttara Kannada");
        city.add("Uttarkashi");
        city.add("Vadodara");
        city.add("Vaishali");
        city.add("Valsad");
        city.add("Varanasi");
        city.add("Vellore");
        city.add("Vidisha");
        city.add("Viluppuram");
        city.add("Virudhunagar");
        city.add("Visakhapatnam");
        city.add("Vizianagaram");
        city.add("Vyara");
        city.add("Warangal");
        city.add("Wardha");
        city.add("Washim");
        city.add("Wayanad");
        city.add("West Champaran");
        city.add("West Delhi");
        city.add("West Garo Hills");
        city.add("West Kameng");
        city.add("West Khasi Hills");
        city.add("West Siang");
        city.add("West Sikkim");
        city.add("West Singhbhum");
        city.add("West Tripura");
        city.add("Wokha");
        city.add("Yadgir");
        city.add("Yamuna Nagar");
        city.add("Yanam");
        city.add("Yavatmal");
        city.add("Zunheboto");
        ArrayAdapter<String> dataAdapter2 = new ArrayAdapter<String>(this,
                android.R.layout.simple_spinner_item, city);
        dataAdapter2.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        se_spinner_city.setAdapter(dataAdapter2);
    }


    public void Search() {
        try {
            final JSONObject jsonObject = new JSONObject();
            jsonObject.put("City", se_spinner_city.getSelectedItem().toString());
            Intent intent = new Intent(SearchActivity.this, SearchDetailActivity.class);
            Bundle b = new Bundle();
            b.putString("Profession", se_spinner_Professions.getSelectedItem().toString());
            b.putString("Batch", se_spinner_Batch.getSelectedItem().toString());
            b.putString("School", se_spinner_institute.getSelectedItem().toString());
            //b.putString("RollNo", se_roll_no.getText().toString().trim());
            b.putString("Department", se_department.getText().toString());
            b.putString("FirstName", se_first_name.getText().toString());
            b.putString("LastName", se_last_name.getText().toString());
            b.putString("Designation", se_designation.getText().toString());
            b.putString("City", se_spinner_city.getSelectedItem().toString());
            b.putString("Screen", "Search results"); //Your id
            intent.putExtras(b); //Put your id to your next Intent
            startActivity(intent);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
